version = 1.8.9

all: paths

directories:
	mkdir -p $(CURDIR)/lib $(CURDIR)/build

downloads: directories
	curl http://googleappengine.googlecode.com/files/google_appengine_$(version).zip -o /tmp/google_appengine_$(version).zip
	unzip -q -o /tmp/google_appengine_$(version).zip -d $(CURDIR)/build

libraries: virtualenv downloads
	mv -v $(CURDIR)/build/google_appengine $(CURDIR)/lib
	ln -sv $(CURDIR)/lib/google_appengine/*.py $(CURDIR)/.env/bin/
	$(CURDIR)/.env/bin/pip install -r $(CURDIR)/resources/requirements.txt

paths: libraries
	cp $(CURDIR)/resources/autogenerated $(CURDIR)/.env/lib/python2.7/site-packages/src.pth
	echo "$(CURDIR)/src/" >> $(CURDIR)/.env/lib/python2.7/site-packages/src.pth
	cp $(CURDIR)/resources/autogenerated $(CURDIR)/.env/lib/python2.7/site-packages/gae.pth
	echo "$(CURDIR)/lib/google_appengine/" >> $(CURDIR)/.env/lib/python2.7/site-packages/gae.pth
	echo "import dev_appserver; dev_appserver.fix_sys_path()" >> $(CURDIR)/.env/lib/python2.7/site-packages/gae.pth

virtualenv:
	virtualenv $(CURDIR)/.env

clean:
	rm -rf $(CURDIR)/.env $(CURDIR)/build $(CURDIR)/lib
